const SWAP = [{'name': 'TokenExchange',
'inputs': [{'type': 'address', 'name': 'buyer', 'indexed': true},
 {'type': 'int128', 'name': 'sold_id', 'indexed': false},
 {'type': 'uint256', 'name': 'tokens_sold', 'indexed': false},
 {'type': 'int128', 'name': 'bought_id', 'indexed': false},
 {'type': 'uint256', 'name': 'tokens_bought', 'indexed': false}],
'anonymous': false,
'type': 'event'},
{'name': 'TokenExchangeUnderlying',
'inputs': [{'type': 'address', 'name': 'buyer', 'indexed': true},
 {'type': 'int128', 'name': 'sold_id', 'indexed': false},
 {'type': 'uint256', 'name': 'tokens_sold', 'indexed': false},
 {'type': 'int128', 'name': 'bought_id', 'indexed': false},
 {'type': 'uint256', 'name': 'tokens_bought', 'indexed': false}],
'anonymous': false,
'type': 'event'},
{'name': 'AddLiquidity',
'inputs': [{'type': 'address', 'name': 'provider', 'indexed': true},
 {'type': 'uint256[4]', 'name': 'token_amounts', 'indexed': false},
 {'type': 'uint256[4]', 'name': 'fees', 'indexed': false},
 {'type': 'uint256', 'name': 'invariant', 'indexed': false},
 {'type': 'uint256', 'name': 'token_supply', 'indexed': false}],
'anonymous': false,
'type': 'event'},
{'name': 'RemoveLiquidity',
'inputs': [{'type': 'address', 'name': 'provider', 'indexed': true},
 {'type': 'uint256[4]', 'name': 'token_amounts', 'indexed': false},
 {'type': 'uint256[4]', 'name': 'fees', 'indexed': false},
 {'type': 'uint256', 'name': 'token_supply', 'indexed': false}],
'anonymous': false,
'type': 'event'},
{'name': 'RemoveLiquidityImbalance',
'inputs': [{'type': 'address', 'name': 'provider', 'indexed': true},
 {'type': 'uint256[4]', 'name': 'token_amounts', 'indexed': false},
 {'type': 'uint256[4]', 'name': 'fees', 'indexed': false},
 {'type': 'uint256', 'name': 'invariant', 'indexed': false},
 {'type': 'uint256', 'name': 'token_supply', 'indexed': false}],
'anonymous': false,
'type': 'event'},
{'name': 'CommitNewAdmin',
'inputs': [{'type': 'uint256',
  'name': 'deadline',
  'indexed': true,
  'unit': 'sec'},
 {'type': 'address', 'name': 'admin', 'indexed': true}],
'anonymous': false,
'type': 'event'},
{'name': 'NewAdmin',
'inputs': [{'type': 'address', 'name': 'admin', 'indexed': true}],
'anonymous': false,
'type': 'event'},
{'name': 'CommitNewParameters',
'inputs': [{'type': 'uint256',
  'name': 'deadline',
  'indexed': true,
  'unit': 'sec'},
 {'type': 'uint256', 'name': 'A', 'indexed': false},
 {'type': 'uint256', 'name': 'fee', 'indexed': false},
 {'type': 'uint256', 'name': 'admin_fee', 'indexed': false}],
'anonymous': false,
'type': 'event'},
{'name': 'NewParameters',
'inputs': [{'type': 'uint256', 'name': 'A', 'indexed': false},
 {'type': 'uint256', 'name': 'fee', 'indexed': false},
 {'type': 'uint256', 'name': 'admin_fee', 'indexed': false}],
'anonymous': false,
'type': 'event'},
{'outputs': [],
'inputs': [{'type': 'address[4]', 'name': '_coins'},
 {'type': 'address[4]', 'name': '_underlying_coins'},
 {'type': 'address', 'name': '_pool_token'},
 {'type': 'uint256', 'name': '_A'},
 {'type': 'uint256', 'name': '_fee'}],
'constant': false,
'payable': false,
'type': 'constructor'},
{'name': 'get_virtual_price',
'outputs': [{'type': 'uint256', 'name': ''}],
'inputs': [],
'constant': true,
'payable': false,
'type': 'function',
'gas': 1536544},
{'name': 'calc_token_amount',
'outputs': [{'type': 'uint256', 'name': ''}],
'inputs': [{'type': 'uint256[4]', 'name': 'amounts'},
 {'type': 'bool', 'name': 'deposit'}],
'constant': true,
'payable': false,
'type': 'function',
'gas': 6069720},
{'name': 'add_liquidity',
'outputs': [],
'inputs': [{'type': 'uint256[4]', 'name': 'amounts'},
 {'type': 'uint256', 'name': 'min_mint_amount'}],
'constant': false,
'payable': false,
'type': 'function',
'gas': 9329222},
{'name': 'get_dy',
'outputs': [{'type': 'uint256', 'name': ''}],
'inputs': [{'type': 'int128', 'name': 'i'},
 {'type': 'int128', 'name': 'j'},
 {'type': 'uint256', 'name': 'dx'}],
'constant': true,
'payable': false,
'type': 'function',
'gas': 3455706},
{'name': 'get_dx',
'outputs': [{'type': 'uint256', 'name': ''}],
'inputs': [{'type': 'int128', 'name': 'i'},
 {'type': 'int128', 'name': 'j'},
 {'type': 'uint256', 'name': 'dy'}],
'constant': true,
'payable': false,
'type': 'function',
'gas': 3455711},
{'name': 'get_dy_underlying',
'outputs': [{'type': 'uint256', 'name': ''}],
'inputs': [{'type': 'int128', 'name': 'i'},
 {'type': 'int128', 'name': 'j'},
 {'type': 'uint256', 'name': 'dx'}],
'constant': true,
'payable': false,
'type': 'function',
'gas': 3455566},
{'name': 'get_dx_underlying',
'outputs': [{'type': 'uint256', 'name': ''}],
'inputs': [{'type': 'int128', 'name': 'i'},
 {'type': 'int128', 'name': 'j'},
 {'type': 'uint256', 'name': 'dy'}],
'constant': true,
'payable': false,
'type': 'function',
'gas': 3455572},
{'name': 'exchange',
'outputs': [],
'inputs': [{'type': 'int128', 'name': 'i'},
 {'type': 'int128', 'name': 'j'},
 {'type': 'uint256', 'name': 'dx'},
 {'type': 'uint256', 'name': 'min_dy'}],
'constant': false,
'payable': false,
'type': 'function',
'gas': 7031987},
{'name': 'exchange_underlying',
'outputs': [],
'inputs': [{'type': 'int128', 'name': 'i'},
 {'type': 'int128', 'name': 'j'},
 {'type': 'uint256', 'name': 'dx'},
 {'type': 'uint256', 'name': 'min_dy'}],
'constant': false,
'payable': false,
'type': 'function',
'gas': 7051995},
{'name': 'remove_liquidity',
'outputs': [],
'inputs': [{'type': 'uint256', 'name': '_amount'},
 {'type': 'uint256[4]', 'name': 'min_amounts'}],
'constant': false,
'payable': false,
'type': 'function',
'gas': 240469},
{'name': 'remove_liquidity_imbalance',
'outputs': [],
'inputs': [{'type': 'uint256[4]', 'name': 'amounts'},
 {'type': 'uint256', 'name': 'max_burn_amount'}],
'constant': false,
'payable': false,
'type': 'function',
'gas': 9328449},
{'name': 'commit_new_parameters',
'outputs': [],
'inputs': [{'type': 'uint256', 'name': 'amplification'},
 {'type': 'uint256', 'name': 'new_fee'},
 {'type': 'uint256', 'name': 'new_admin_fee'}],
'constant': false,
'payable': false,
'type': 'function',
'gas': 145927},
{'name': 'apply_new_parameters',
'outputs': [],
'inputs': [],
'constant': false,
'payable': false,
'type': 'function',
'gas': 133542},
{'name': 'revert_new_parameters',
'outputs': [],
'inputs': [],
'constant': false,
'payable': false,
'type': 'function',
'gas': 21865},
{'name': 'commit_transfer_ownership',
'outputs': [],
'inputs': [{'type': 'address', 'name': '_owner'}],
'constant': false,
'payable': false,
'type': 'function',
'gas': 74542},
{'name': 'apply_transfer_ownership',
'outputs': [],
'inputs': [],
'constant': false,
'payable': false,
'type': 'function',
'gas': 60598},
{'name': 'revert_transfer_ownership',
'outputs': [],
'inputs': [],
'constant': false,
'payable': false,
'type': 'function',
'gas': 21955},
{'name': 'withdraw_admin_fees',
'outputs': [],
'inputs': [],
'constant': false,
'payable': false,
'type': 'function',
'gas': 22727},
{'name': 'kill_me',
'outputs': [],
'inputs': [],
'constant': false,
'payable': false,
'type': 'function',
'gas': 37908},
{'name': 'unkill_me',
'outputs': [],
'inputs': [],
'constant': false,
'payable': false,
'type': 'function',
'gas': 22045},
{'name': 'coins',
'outputs': [{'type': 'address', 'name': ''}],
'inputs': [{'type': 'int128', 'name': 'arg0'}],
'constant': true,
'payable': false,
'type': 'function',
'gas': 2220},
{'name': 'underlying_coins',
'outputs': [{'type': 'address', 'name': ''}],
'inputs': [{'type': 'int128', 'name': 'arg0'}],
'constant': true,
'payable': false,
'type': 'function',
'gas': 2250},
{'name': 'balances',
'outputs': [{'type': 'uint256', 'name': ''}],
'inputs': [{'type': 'int128', 'name': 'arg0'}],
'constant': true,
'payable': false,
'type': 'function',
'gas': 2280},
{'name': 'A',
'outputs': [{'type': 'uint256', 'name': ''}],
'inputs': [],
'constant': true,
'payable': false,
'type': 'function',
'gas': 2111},
{'name': 'fee',
'outputs': [{'type': 'uint256', 'name': ''}],
'inputs': [],
'constant': true,
'payable': false,
'type': 'function',
'gas': 2141},
{'name': 'admin_fee',
'outputs': [{'type': 'uint256', 'name': ''}],
'inputs': [],
'constant': true,
'payable': false,
'type': 'function',
'gas': 2171},
{'name': 'owner',
'outputs': [{'type': 'address', 'name': ''}],
'inputs': [],
'constant': true,
'payable': false,
'type': 'function',
'gas': 2201},
{'name': 'admin_actions_deadline',
'outputs': [{'type': 'uint256', 'unit': 'sec', 'name': ''}],
'inputs': [],
'constant': true,
'payable': false,
'type': 'function',
'gas': 2231},
{'name': 'transfer_ownership_deadline',
'outputs': [{'type': 'uint256', 'unit': 'sec', 'name': ''}],
'inputs': [],
'constant': true,
'payable': false,
'type': 'function',
'gas': 2261},
{'name': 'future_A',
'outputs': [{'type': 'uint256', 'name': ''}],
'inputs': [],
'constant': true,
'payable': false,
'type': 'function',
'gas': 2291},
{'name': 'future_fee',
'outputs': [{'type': 'uint256', 'name': ''}],
'inputs': [],
'constant': true,
'payable': false,
'type': 'function',
'gas': 2321},
{'name': 'future_admin_fee',
'outputs': [{'type': 'uint256', 'name': ''}],
'inputs': [],
'constant': true,
'payable': false,
'type': 'function',
'gas': 2351},
{'name': 'future_owner',
'outputs': [{'type': 'address', 'name': ''}],
'inputs': [],
'constant': true,
'payable': false,
'type': 'function',
'gas': 2381}]

const DEPOSIT = [{'outputs': [],
'inputs': [{'type': 'address[4]', 'name': '_coins'},
 {'type': 'address[4]', 'name': '_underlying_coins'},
 {'type': 'address', 'name': '_curve'},
 {'type': 'address', 'name': '_token'}],
'constant': false,
'payable': false,
'type': 'constructor'},
{'name': 'add_liquidity',
'outputs': [],
'inputs': [{'type': 'uint256[4]', 'name': 'uamounts'},
 {'type': 'uint256', 'name': 'min_mint_amount'}],
'constant': false,
'payable': false,
'type': 'function',
'gas': 164595},
{'name': 'remove_liquidity',
'outputs': [],
'inputs': [{'type': 'uint256', 'name': '_amount'},
 {'type': 'uint256[4]', 'name': 'min_uamounts'}],
'constant': false,
'payable': false,
'type': 'function',
'gas': 99556},
{'name': 'remove_liquidity_imbalance',
'outputs': [],
'inputs': [{'type': 'uint256[4]', 'name': 'uamounts'},
 {'type': 'uint256', 'name': 'max_burn_amount'}],
'constant': false,
'payable': false,
'type': 'function',
'gas': 124362},
{'name': 'calc_withdraw_one_coin',
'outputs': [{'type': 'uint256', 'name': ''}],
'inputs': [{'type': 'uint256', 'name': '_token_amount'},
 {'type': 'int128', 'name': 'i'}],
'constant': true,
'payable': false,
'type': 'function',
'gas': 3877368},
{'name': 'remove_liquidity_one_coin',
'outputs': [],
'inputs': [{'type': 'uint256', 'name': '_token_amount'},
 {'type': 'int128', 'name': 'i'},
 {'type': 'uint256', 'name': 'min_uamount'}],
'constant': false,
'payable': false,
'type': 'function'},
{'name': 'remove_liquidity_one_coin',
'outputs': [],
'inputs': [{'type': 'uint256', 'name': '_token_amount'},
 {'type': 'int128', 'name': 'i'},
 {'type': 'uint256', 'name': 'min_uamount'},
 {'type': 'bool', 'name': 'donate_dust'}],
'constant': false,
'payable': false,
'type': 'function'},
{'name': 'withdraw_donated_dust',
'outputs': [],
'inputs': [],
'constant': false,
'payable': false,
'type': 'function',
'gas': 64033},
{'name': 'coins',
'outputs': [{'type': 'address', 'name': ''}],
'inputs': [{'type': 'int128', 'name': 'arg0'}],
'constant': true,
'payable': false,
'type': 'function',
'gas': 1740},
{'name': 'underlying_coins',
'outputs': [{'type': 'address', 'name': ''}],
'inputs': [{'type': 'int128', 'name': 'arg0'}],
'constant': true,
'payable': false,
'type': 'function',
'gas': 1770},
{'name': 'curve',
'outputs': [{'type': 'address', 'name': ''}],
'inputs': [],
'constant': true,
'payable': false,
'type': 'function',
'gas': 1601},
{'name': 'token',
'outputs': [{'type': 'address', 'name': ''}],
'inputs': [],
'constant': true,
'payable': false,
'type': 'function',
'gas': 1631}]

export default {
  SWAP,
  DEPOSIT
}